swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/transactions:
    post:
      tags:
        - User Module
      summary: Get Transactions
      description: API for Get Transactions
      produces:
        - application/json
      responses:
        "200":
          description: Get Transactions Successfully
          schema:
            $ref: "#/definitions/Transactions"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  definitions:
    Transaction:
      type: object
      properties:
        amount:
          type: number
        name:
          type: string
    Transactions:
      type: array
      items:
        $ref: "#/definitions/Transaction"
    ApiResponse:
      type: object
      properties:
        message:
          type: string
        status:
          type: string
          enum:
            - success
            - error
  